spring:
  application:
    name: spring-boot-template
    jackson:
      property-naming-strategy: SNAKE_CASE
    flyway:
      locations: classpath:/db/migration
      schemas: employees
      baselineOnMigrate: true
      enabled: true
